<?php
/**
 * @copyright 2015 iMarc LLC
 * @author Kevin Hamer [kh] <kevin@imarc.net>
 * @license Apache (see LICENSE file)
 */

namespace Craft;

use PHPUnit_Framework_TestCase;

/**
 * CraftSassPluginTest verifies that the sass compiler is working properly by
 * stubbing out some of the Craft classes.
 */
class CraftSassPluginTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @runInSeparateProcess
	 */
    public function testCompilation()
    {
        $css = craft()->sass_compiler->compile('sample.scss');

        // remove the comment line generated by leafo
        $css = $this->removeLines($css, 2);

        $this->assertEquals(file_get_contents(__DIR__ . '/result.css'), $css);
    }

    /**
     * Helper to remove lines from a string
     *
     * @param string the input
     * @param integer the number of lines to remove
     * @return string the output without the lines
     */
    private function removeLines($string, $lines)
    {
        return implode("\n", array_slice(explode("\n", $string), $lines));
    }
}
